# Generated by Django 4.1.2 on 2022-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboard',
            name='mytitle',
            field=models.CharField(max_length=300),
        ),
    ]
