# Generated by Django 4.1.2 on 2022-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myname", models.CharField(max_length=100)),
                ("mytitle", models.CharField(max_length=300)),
                ("mycontent", models.CharField(max_length=2000)),
                ("mydate", models.DateTimeField()),
            ],
        ),
    ]
